##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
url: https://ahva-ubc.github.io
baseurl: /Heaven-and-Earth/
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh
# location of code, the full url to your github repository
source-code: https://github.com/ahva-ubc/Heaven-and-Earth.git

##########
# SITE SETTINGS
#
# title of site appears in banner
title: "Heaven and Earth"
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Renaissance Art and Culture in Northern Europe
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Painting, sculpture, and graphic art in France, the Netherlands, Germany, and England in the 15th and 16th centuries, with special emphasis on the major figures of this period, from van Eyck and van der Weyden to Grunewald, Bosch, Durer, Holbein, and Pieter Bruegel. Topics covered include the transformation of craft into art as a self-reflective and intellectual practice (Kunst); the emergence of oil painting as a transformative media; the German sculpted altarpiece and the triptych as Northern genres of art; visual culture and the Protestant Reformation; the emergence of graphic culture and the fine art print; witchcraft and mystical nature in German art; and the birth of secular art: portraiture, landscape, and scenes of everyday life."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Joseph Monteyne

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection)
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: heaven_earth
encoding: utf-8

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id:

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true

##########
# BUILD SETTINGS
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
