##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: ARTH 321 Public and Private Bodies
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Italian Renaissance Art and Culture 1350-1550
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Instructor: <a href="https://ahva.ubc.ca/profile/joseph-monteyne/">Joseph Monteyne</a>

Teaching Assistant:
 
This course explores changing roles for visual art and culture within communes, courts, religious practices and private lives in Renaissance Italy. New patrons and uses for artworks prompted a wealth of artistic activity that defined and shaped contemporary values, ideas, perceptions, beliefs, and identities. For example, bankers, merchants, and mercenaries exploited the power of art and architecture to forge and to buttress their public image and family name. Religious institutions and commercial guilds similarly propagated their claims through visual imagery. Furthermore, gender, sexuality and space provided the frameworks through which power and legitimacy were both staged and contested during a pivotal century that was shaped by the printing press, the discovery of worlds previously unknown to Europeans, the invasion of Italy by foreigners, the Reformation and Counter- Reformation, and the rising status of the artist."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: AHVA VRC

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: public-and-private

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
